{
    "version": "3.7",
    "services":
    {
        "rethink-backup-cloud":
        {
            "image": "eu.gcr.io/rethink-backup-cloud/rethink-backup-cloud",
            "build":
            {
                "context": "./"
            },
            "volumes":
            [
                "./backup_config.json:/home/root/App/config.json"
            ],
            "restart": "unless-stopped"
        }
    }
}